// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnV9ECj4lo87BfYwbtmfR70bpkgy24T3Y',
    appId: '1:248199492725:web:b4b2e33288e3f169a7b43c',
    messagingSenderId: '248199492725',
    projectId: 'mykantin-app',
    authDomain: 'mykantin-app.firebaseapp.com',
    storageBucket: 'mykantin-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn7-8N-Oft0CvN__K314FRYYXAk5kmRf4',
    appId: '1:248199492725:android:39fa1f8bf16571b8a7b43c',
    messagingSenderId: '248199492725',
    projectId: 'mykantin-app',
    storageBucket: 'mykantin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWaeez72fQLdBiMns9gxgHmAbIvIvFxWU',
    appId: '1:248199492725:ios:31839b9646dd3496a7b43c',
    messagingSenderId: '248199492725',
    projectId: 'mykantin-app',
    storageBucket: 'mykantin-app.firebasestorage.app',
    iosBundleId: 'com.example.mykantin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWaeez72fQLdBiMns9gxgHmAbIvIvFxWU',
    appId: '1:248199492725:ios:31839b9646dd3496a7b43c',
    messagingSenderId: '248199492725',
    projectId: 'mykantin-app',
    storageBucket: 'mykantin-app.firebasestorage.app',
    iosBundleId: 'com.example.mykantin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnV9ECj4lo87BfYwbtmfR70bpkgy24T3Y',
    appId: '1:248199492725:web:d8f373962b65b72ba7b43c',
    messagingSenderId: '248199492725',
    projectId: 'mykantin-app',
    authDomain: 'mykantin-app.firebaseapp.com',
    storageBucket: 'mykantin-app.firebasestorage.app',
  );
}
